name: Build, Test, and Release Installer

on:
  push:
    tags:
      - 'v*'  # Trigger workflow on version tags (e.g., v1.0.0)

jobs:
  build_and_test:
    name: Build and Test Application
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0  # Specify the .NET version

      # Step 3: Restore dependencies
      - name: Restore Dependencies
        run: dotnet restore

      # Step 4: Build the application
      - name: Build Application
        run: dotnet build -c Release

      # Step 5: Run Tests
      - name: Run Tests
        run: dotnet test --no-build --verbosity normal

  package_installer:
    name: Package Application into Installer
    needs: build_and_test
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Compile .ISS to .EXE Installer using Inno Setup
      - name: Compile Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: src/setup.iss  # Adjust to the location of your .iss file
          options: /O+

      # Step 3: Create a GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: "Automated release of the installer."
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Upload Installer to Release
      - name: Upload Installer
        uses: actions/upload-release-asset@v1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_id: ${{ steps.create_release.outputs.id }}
          asset_path: src/*.exe  # Adjust to match the generated installer location
          asset_name: ${{ github.ref_name }}_Installer.exe
          content_type: application/vnd.microsoft.portable-executable
