name: Build, Sign, and Release Installer

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      # Step 3: Restore dependencies and publish
      - name: Publish Application with Runtime
        run: dotnet publish -c Release -o output --self-contained --runtime win-x64

      # Step 4: Generate a Self-Signed Certificate
      - name: Generate Self-Signed Certificate
        run: |
          $cert = New-SelfSignedCertificate -Type CodeSigning -Subject "CN=WorkflowAutomation" -CertStoreLocation "Cert:\LocalMachine\My"
          $thumbprint = $cert.Thumbprint
          Export-PfxCertificate -Cert "Cert:\LocalMachine\My\$thumbprint" -FilePath "output/self-signed-cert.pfx" -Password (ConvertTo-SecureString -String "password" -Force -AsPlainText)
        shell: pwsh

      # Step 5: Create Inno Setup Installer
      - name: Create Inno Setup Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: setup.iss
          options: /Q

      # Step 6: Generate Changelog
      - name: Generate Changelog
        id: changelog
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^)
          echo "Previous Tag: $PREV_TAG"
          gh pr list --search "is:merged base:$PREV_TAG" --json title,number,labels --jq '
            [.[] | 
              {
                title: .title,
                number: .number,
                category: (
                  if any(.labels[]; .name == "breaking change") then "Breaking Changes" 
                  elif any(.labels[]; .name == "enhancement") then "New Features" 
                  elif any(.labels[]; .name == "bug") then "Bug Fixes" 
                  else "Other Changes" 
                  end
                )
              }
            ]' > changelog.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash

      # Step 7: Format Changelog and Create Release
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            ## Changelog
            ${{ steps.changelog.outputs.body }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 8: Upload Installer to Release
      - name: Upload Installer to Release
        uses: actions/upload-release-asset@v1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_id: ${{ steps.create-release.outputs.id }}
          asset_path: output/WorkflowAutomation_Installer.exe
          asset_name: WorkflowAutomation_Installer.exe
          content_type: application/vnd.microsoft.portable-executable
