name: Build, Test, and Publish Installer

on:
  push:
    tags:
      - 'v*'  # Trigger workflow on version tags (e.g., v1.0.0)

jobs:
  build_and_test:
    name: Build and Test Application
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet build -c Release

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal

  package_installer:
    name: Package and Publish Installer
    needs: build_and_test
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compile Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: installer.iss  # Correct path to the .iss file
          options: /O+

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: "This release includes the application and the necessary .NET Core Runtime 8 installation."
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Installer
        uses: actions/upload-release-asset@v1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_id: ${{ steps.create_release.outputs.id }}
          asset_path: output/WorkflowAutomation-Installer.exe  # Path to the generated installer
          asset_name: ${{ github.ref_name }}_Installer.exe
          content_type: application/vnd.microsoft.portable-executable
